import json
import generate_exhaustive_atlas

raw_atlas = generate_exhaustive_atlas.ATLAS_177

# Mapping of country currencies and timezones
# Comprehensive database covering all 177 countries & territories
COUNTRY_EXTRAS = {
  "Afghanistan": {"tz": "Asia/Kabul", "curr_es": "Afgani afgano (AFN)", "curr_en": "Afghan Afghani (AFN)"},
  "Albania": {"tz": "Europe/Tirane", "curr_es": "Lek albanés (ALL)", "curr_en": "Albanian Lek (ALL)"},
  "Algeria": {"tz": "Africa/Algiers", "curr_es": "Dinar argelino (DZD)", "curr_en": "Algerian Dinar (DZD)"},
  "Angola": {"tz": "Africa/Luanda", "curr_es": "Kwanza angoleño (AOA)", "curr_en": "Angolan Kwanza (AOA)"},
  "Antarctica": {"tz": "Antarctica/McMurdo", "curr_es": "Monedas internacionales", "curr_en": "International currencies"},
  "Argentina": {"tz": "America/Argentina/Buenos_Aires", "curr_es": "Peso argentino (ARS)", "curr_en": "Argentine Peso (ARS)"},
  "Armenia": {"tz": "Asia/Yerevan", "curr_es": "Dram armenio (AMD)", "curr_en": "Armenian Dram (AMD)"},
  "Australia": {"tz": "Australia/Sydney", "curr_es": "Dólar australiano (AUD)", "curr_en": "Australian Dollar (AUD)"},
  "Austria": {"tz": "Europe/Vienna", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Azerbaijan": {"tz": "Asia/Baku", "curr_es": "Manat azerbaiyano (AZN)", "curr_en": "Azerbaijani Manat (AZN)"},
  "Bahamas": {"tz": "America/Nassau", "curr_es": "Dólar bahameño (BSD)", "curr_en": "Bahamian Dollar (BSD)"},
  "Bangladesh": {"tz": "Asia/Dhaka", "curr_es": "Taka bangladesí (BDT)", "curr_en": "Bangladeshi Taka (BDT)"},
  "Belarus": {"tz": "Europe/Minsk", "curr_es": "Rublo bielorruso (BYN)", "curr_en": "Belarusian Ruble (BYN)"},
  "Belgium": {"tz": "Europe/Brussels", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Belize": {"tz": "America/Belize", "curr_es": "Dólar beliceño (BZD)", "curr_en": "Belize Dollar (BZD)"},
  "Benin": {"tz": "Africa/Porto-Novo", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Bhutan": {"tz": "Asia/Thimphu", "curr_es": "Ngultrum butanés (BTN)", "curr_en": "Bhutanese Ngultrum (BTN)"},
  "Bolivia": {"tz": "America/La_Paz", "curr_es": "Boliviano (BOB)", "curr_en": "Bolivian Boliviano (BOB)"},
  "Bosnia and Herz.": {"tz": "Europe/Sarajevo", "curr_es": "Marco convertible (BAM)", "curr_en": "Convertible Mark (BAM)"},
  "Botswana": {"tz": "Africa/Gaborone", "curr_es": "Pula de Botsuana (BWP)", "curr_en": "Botswana Pula (BWP)"},
  "Brazil": {"tz": "America/Sao_Paulo", "curr_es": "Real brasileño (BRL)", "curr_en": "Brazilian Real (BRL)"},
  "Brunei": {"tz": "Asia/Brunei", "curr_es": "Dólar de Brunéi (BND)", "curr_en": "Brunei Dollar (BND)"},
  "Bulgaria": {"tz": "Europe/Sofia", "curr_es": "Lev búlgaro (BGN)", "curr_en": "Bulgarian Lev (BGN)"},
  "Burkina Faso": {"tz": "Africa/Ouagadougou", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Burundi": {"tz": "Africa/Bujumbura", "curr_es": "Franco burundés (BIF)", "curr_en": "Burundian Franc (BIF)"},
  "Cambodia": {"tz": "Asia/Phnom_Penh", "curr_es": "Riel camboyano (KHR)", "curr_en": "Cambodian Riel (KHR)"},
  "Cameroon": {"tz": "Africa/Douala", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Canada": {"tz": "America/Toronto", "curr_es": "Dólar canadiense (CAD)", "curr_en": "Canadian Dollar (CAD)"},
  "Central African Rep.": {"tz": "Africa/Bangui", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Chad": {"tz": "Africa/Ndjamena", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Chile": {"tz": "America/Santiago", "curr_es": "Peso chileno (CLP)", "curr_en": "Chilean Peso (CLP)"},
  "China": {"tz": "Asia/Shanghai", "curr_es": "Yuan chino (CNY)", "curr_en": "Chinese Yuan (CNY)"},
  "Colombia": {"tz": "America/Bogota", "curr_es": "Peso colombiano (COP)", "curr_en": "Colombian Peso (COP)"},
  "Congo": {"tz": "Africa/Brazzaville", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Costa Rica": {"tz": "America/Costa_Rica", "curr_es": "Colón costarricense (CRC)", "curr_en": "Costa Rican Colón (CRC)"},
  "Croatia": {"tz": "Europe/Zagreb", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Cuba": {"tz": "America/Havana", "curr_es": "Peso cubano (CUP)", "curr_en": "Cuban Peso (CUP)"},
  "Cyprus": {"tz": "Asia/Nicosia", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Czechia": {"tz": "Europe/Prague", "curr_es": "Corona checa (CZK)", "curr_en": "Czech Koruna (CZK)"},
  "Côte d'Ivoire": {"tz": "Africa/Abidjan", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Dem. Rep. Congo": {"tz": "Africa/Kinshasa", "curr_es": "Franco congoleño (CDF)", "curr_en": "Congolese Franc (CDF)"},
  "Denmark": {"tz": "Europe/Copenhagen", "curr_es": "Corona danesa (DKK)", "curr_en": "Danish Krone (DKK)"},
  "Djibouti": {"tz": "Africa/Djibouti", "curr_es": "Franco yibutiano (DJF)", "curr_en": "Djiboutian Franc (DJF)"},
  "Dominican Rep.": {"tz": "America/Santo_Domingo", "curr_es": "Peso dominicano (DOP)", "curr_en": "Dominican Peso (DOP)"},
  "Ecuador": {"tz": "America/Guayaquil", "curr_es": "Dólar estadounidense (USD)", "curr_en": "United States Dollar (USD)"},
  "Egypt": {"tz": "Africa/Cairo", "curr_es": "Libra egipcia (EGP)", "curr_en": "Egyptian Pound (EGP)"},
  "El Salvador": {"tz": "America/El_Salvador", "curr_es": "Dólar estadounidense (USD)", "curr_en": "United States Dollar (USD)"},
  "Eq. Guinea": {"tz": "Africa/Malabo", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Eritrea": {"tz": "Africa/Asmara", "curr_es": "Nakfa eritreo (ERN)", "curr_en": "Eritrean Nakfa (ERN)"},
  "Estonia": {"tz": "Europe/Tallinn", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Eswatini": {"tz": "Africa/Mbabane", "curr_es": "Lilangeni suazi (SZL)", "curr_en": "Swazi Lilangeni (SZL)"},
  "Ethiopia": {"tz": "Africa/Addis_Ababa", "curr_es": "Birr etíope (ETB)", "curr_en": "Ethiopian Birr (ETB)"},
  "Falkland Is.": {"tz": "Atlantic/Stanley", "curr_es": "Peso argentino (ARS)", "curr_en": "Argentine Peso (ARS)"},
  "Fiji": {"tz": "Pacific/Fiji", "curr_es": "Dólar fiyiano (FJD)", "curr_en": "Fijian Dollar (FJD)"},
  "Finland": {"tz": "Europe/Helsinki", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Fr. S. Antarctic Lands": {"tz": "Indian/Kerguelen", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "France": {"tz": "Europe/Paris", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Gabon": {"tz": "Africa/Libreville", "curr_es": "Franco CFA (XAF)", "curr_en": "Central African CFA Franc (XAF)"},
  "Gambia": {"tz": "Africa/Banjul", "curr_es": "Dalasi gambiano (GMD)", "curr_en": "Gambian Dalasi (GMD)"},
  "Georgia": {"tz": "Asia/Tbilisi", "curr_es": "Lari georgiano (GEL)", "curr_en": "Georgian Lari (GEL)"},
  "Germany": {"tz": "Europe/Berlin", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Ghana": {"tz": "Africa/Accra", "curr_es": "Cedi ghanés (GHS)", "curr_en": "Ghanaian Cedi (GHS)"},
  "Greece": {"tz": "Europe/Athens", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Greenland": {"tz": "America/Nuuk", "curr_es": "Corona danesa (DKK)", "curr_en": "Danish Krone (DKK)"},
  "Guatemala": {"tz": "America/Guatemala", "curr_es": "Quetzal guatemalteco (GTQ)", "curr_en": "Guatemalan Quetzal (GTQ)"},
  "Guinea": {"tz": "Africa/Conakry", "curr_es": "Franco guineano (GNF)", "curr_en": "Guinean Franc (GNF)"},
  "Guinea-Bissau": {"tz": "Africa/Bissau", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Guyana": {"tz": "America/Guyana", "curr_es": "Dólar guyanés (GYD)", "curr_en": "Guyanese Dollar (GYD)"},
  "Haiti": {"tz": "America/Port-au-Prince", "curr_es": "Gourde haitiano (HTG)", "curr_en": "Haitian Gourde (HTG)"},
  "Honduras": {"tz": "America/Tegucigalpa", "curr_es": "Lempira hondureña (HNL)", "curr_en": "Honduran Lempira (HNL)"},
  "Hungary": {"tz": "Europe/Budapest", "curr_es": "Forinto húngaro (HUF)", "curr_en": "Hungarian Forint (HUF)"},
  "Iceland": {"tz": "Atlantic/Reykjavik", "curr_es": "Corona islandesa (ISK)", "curr_en": "Icelandic Króna (ISK)"},
  "India": {"tz": "Asia/Kolkata", "curr_es": "Rupia india (INR)", "curr_en": "Indian Rupee (INR)"},
  "Indonesia": {"tz": "Asia/Jakarta", "curr_es": "Rupia indonesia (IDR)", "curr_en": "Indonesian Rupiah (IDR)"},
  "Iran": {"tz": "Asia/Tehran", "curr_es": "Rial iraní (IRR)", "curr_en": "Iranian Rial (IRR)"},
  "Iraq": {"tz": "Asia/Baghdad", "curr_es": "Dinar iraquí (IQD)", "curr_en": "Iraqi Dinar (IQD)"},
  "Ireland": {"tz": "Europe/Dublin", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Israel": {"tz": "Asia/Jerusalem", "curr_es": "Nuevo séquel israelí (ILS)", "curr_en": "Israeli New Shekel (ILS)"},
  "Italy": {"tz": "Europe/Rome", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Jamaica": {"tz": "America/Jamaica", "curr_es": "Dólar jamaiquino (JMD)", "curr_en": "Jamaican Dollar (JMD)"},
  "Japan": {"tz": "Asia/Tokyo", "curr_es": "Yen japonés (JPY)", "curr_en": "Japanese Yen (JPY)"},
  "Jordan": {"tz": "Asia/Amman", "curr_es": "Dinar jordano (JOD)", "curr_en": "Jordanian Dinar (JOD)"},
  "Kazakhstan": {"tz": "Asia/Almaty", "curr_es": "Tenge kazajo (KZT)", "curr_en": "Kazakhstani Tenge (KZT)"},
  "Kenya": {"tz": "Africa/Nairobi", "curr_es": "Chelín keniano (KES)", "curr_en": "Kenyan Shilling (KES)"},
  "Kosovo": {"tz": "Europe/Belgrade", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Kuwait": {"tz": "Asia/Kuwait", "curr_es": "Dinar kuwaití (KWD)", "curr_en": "Kuwaiti Dinar (KWD)"},
  "Kyrgyzstan": {"tz": "Asia/Bishkek", "curr_es": "Som kirguís (KGS)", "curr_en": "Kyrgyzstani Som (KGS)"},
  "Laos": {"tz": "Asia/Vientiane", "curr_es": "Kip laosiano (LAK)", "curr_en": "Lao Kip (LAK)"},
  "Latvia": {"tz": "Europe/Riga", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Lebanon": {"tz": "Asia/Beirut", "curr_es": "Libra libanesa (LBP)", "curr_en": "Lebanese Pound (LBP)"},
  "Lesotho": {"tz": "Africa/Maseru", "curr_es": "Loti de Lesoto (LSL)", "curr_en": "Lesotho Loti (LSL)"},
  "Liberia": {"tz": "Africa/Monrovia", "curr_es": "Dólar liberiano (LRD)", "curr_en": "Liberian Dollar (LRD)"},
  "Libya": {"tz": "Africa/Tripoli", "curr_es": "Dinar libio (LYD)", "curr_en": "Libyan Dinar (LYD)"},
  "Lithuania": {"tz": "Europe/Vilnius", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Luxembourg": {"tz": "Europe/Luxembourg", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Madagascar": {"tz": "Indian/Antananarivo", "curr_es": "Ariary malgache (MGA)", "curr_en": "Malagasy Ariary (MGA)"},
  "Malawi": {"tz": "Africa/Blantyre", "curr_es": "Kwacha malauí (MWK)", "curr_en": "Malawian Kwacha (MWK)"},
  "Malaysia": {"tz": "Asia/Kuala_Lumpur", "curr_es": "Ringgit malasio (MYR)", "curr_en": "Malaysian Ringgit (MYR)"},
  "Mali": {"tz": "Africa/Bamako", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Mauritania": {"tz": "Africa/Nouakchott", "curr_es": "Uguiya mauritana (MRU)", "curr_en": "Mauritanian Ouguiya (MRU)"},
  "Mexico": {"tz": "America/Mexico_City", "curr_es": "Peso mexicano (MXN)", "curr_en": "Mexican Peso (MXN)"},
  "Moldova": {"tz": "Europe/Chisinau", "curr_es": "Leu moldavo (MDL)", "curr_en": "Moldovan Leu (MDL)"},
  "Mongolia": {"tz": "Asia/Ulaanbaatar", "curr_es": "Tugrik mongol (MNT)", "curr_en": "Mongolian Tögrög (MNT)"},
  "Montenegro": {"tz": "Europe/Podgorica", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Morocco": {"tz": "Africa/Casablanca", "curr_es": "Dírham marroquí (MAD)", "curr_en": "Moroccan Dirham (MAD)"},
  "Mozambique": {"tz": "Africa/Maputo", "curr_es": "Metical mozambiqueño (MZN)", "curr_en": "Mozambican Metical (MZN)"},
  "Myanmar": {"tz": "Asia/Yangon", "curr_es": "Kyat birmano (MMK)", "curr_en": "Myanmar Kyat (MMK)"},
  "N. Cyprus": {"tz": "Asia/Nicosia", "curr_es": "Lira turca (TRY)", "curr_en": "Turkish Lira (TRY)"},
  "Namibia": {"tz": "Africa/Windhoek", "curr_es": "Dólar namibio (NAD)", "curr_en": "Namibian Dollar (NAD)"},
  "Nepal": {"tz": "Asia/Kathmandu", "curr_es": "Rupia nepalí (NPR)", "curr_en": "Nepalese Rupee (NPR)"},
  "Netherlands": {"tz": "Europe/Amsterdam", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "New Caledonia": {"tz": "Pacific/Noumea", "curr_es": "Franco CFP (XPF)", "curr_en": "CFP Franc (XPF)"},
  "New Zealand": {"tz": "Pacific/Auckland", "curr_es": "Dólar neozelandés (NZD)", "curr_en": "New Zealand Dollar (NZD)"},
  "Nicaragua": {"tz": "America/Managua", "curr_es": "Córdoba nicaragüense (NIO)", "curr_en": "Nicaraguan Córdoba (NIO)"},
  "Niger": {"tz": "Africa/Niamey", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Nigeria": {"tz": "Africa/Lagos", "curr_es": "Naira nigeriana (NGN)", "curr_en": "Nigerian Naira (NGN)"},
  "North Korea": {"tz": "Asia/Pyongyang", "curr_es": "Won norcoreano (KPW)", "curr_en": "North Korean Won (KPW)"},
  "North Macedonia": {"tz": "Europe/Skopje", "curr_es": "Denar macedonio (MKD)", "curr_en": "Macedonian Denar (MKD)"},
  "Norway": {"tz": "Europe/Oslo", "curr_es": "Corona noruega (NOK)", "curr_en": "Norwegian Krone (NOK)"},
  "Oman": {"tz": "Asia/Muscat", "curr_es": "Rial omaní (OMR)", "curr_en": "Omani Rial (OMR)"},
  "Pakistan": {"tz": "Asia/Karachi", "curr_es": "Rupia pakistaní (PKR)", "curr_en": "Pakistani Rupee (PKR)"},
  "Palestine": {"tz": "Asia/Gaza", "curr_es": "Shekel / Dinar", "curr_en": "Shekel / Dinar"},
  "Panama": {"tz": "America/Panama", "curr_es": "Balboa panameño (PAB)", "curr_en": "Panamanian Balboa (PAB)"},
  "Papua New Guinea": {"tz": "Pacific/Port_Moresby", "curr_es": "Kina de Papúa Nueva Guinea (PGK)", "curr_en": "Papua New Guinean Kina (PGK)"},
  "Paraguay": {"tz": "America/Asuncion", "curr_es": "Guaraní paraguayo (PYG)", "curr_en": "Paraguayan Guaraní (PYG)"},
  "Peru": {"tz": "America/Lima", "curr_es": "Sol peruano (PEN)", "curr_en": "Peruvian Sol (PEN)"},
  "Philippines": {"tz": "Asia/Manila", "curr_es": "Peso filipino (PHP)", "curr_en": "Philippine Peso (PHP)"},
  "Poland": {"tz": "Europe/Warsaw", "curr_es": "Zloty polaco (PLN)", "curr_en": "Polish Zloty (PLN)"},
  "Portugal": {"tz": "Europe/Lisbon", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Puerto Rico": {"tz": "America/Puerto_Rico", "curr_es": "Dólar estadounidense (USD)", "curr_en": "United States Dollar (USD)"},
  "Qatar": {"tz": "Asia/Qatar", "curr_es": "Riyal catarí (QAR)", "curr_en": "Qatari Riyal (QAR)"},
  "Romania": {"tz": "Europe/Bucharest", "curr_es": "Leu rumano (RON)", "curr_en": "Romanian Leu (RON)"},
  "Russia": {"tz": "Europe/Moscow", "curr_es": "Rublo ruso (RUB)", "curr_en": "Russian Ruble (RUB)"},
  "Rwanda": {"tz": "Africa/Kigali", "curr_es": "Franco ruandés (RWF)", "curr_en": "Rwandan Franc (RWF)"},
  "Saudi Arabia": {"tz": "Asia/Riyadh", "curr_es": "Riyal saudí (SAR)", "curr_en": "Saudi Riyal (SAR)"},
  "Senegal": {"tz": "Africa/Dakar", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Serbia": {"tz": "Europe/Belgrade", "curr_es": "Dinar serbio (RSD)", "curr_en": "Serbian Dinar (RSD)"},
  "Sierra Leone": {"tz": "Africa/Freetown", "curr_es": "Leone de Sierra Leona (SLE)", "curr_en": "Sierra Leonean Leone (SLE)"},
  "Slovakia": {"tz": "Europe/Bratislava", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Slovenia": {"tz": "Europe/Ljubljana", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Solomon Is.": {"tz": "Pacific/Guadalcanal", "curr_es": "Dólar de las Islas Salomón (SBD)", "curr_en": "Solomon Islands Dollar (SBD)"},
  "Somalia": {"tz": "Africa/Mogadishu", "curr_es": "Chelín somalí (SOS)", "curr_en": "Somali Shilling (SOS)"},
  "Somaliland": {"tz": "Africa/Mogadishu", "curr_es": "Chelín de Somalilandia", "curr_en": "Somaliland Shilling"},
  "South Africa": {"tz": "Africa/Johannesburg", "curr_es": "Rand sudafricano (ZAR)", "curr_en": "South African Rand (ZAR)"},
  "South Korea": {"tz": "Asia/Seoul", "curr_es": "Won surcoreano (KRW)", "curr_en": "South Korean Won (KRW)"},
  "South Sudan": {"tz": "Africa/Juba", "curr_es": "Libra sursudanesa (SSP)", "curr_en": "South Sudanese Pound (SSP)"},
  "Spain": {"tz": "Europe/Madrid", "curr_es": "Euro (EUR)", "curr_en": "Euro (EUR)"},
  "Sri Lanka": {"tz": "Asia/Colombo", "curr_es": "Rupia de Sri Lanka (LKR)", "curr_en": "Sri Lankan Rupee (LKR)"},
  "Sudan": {"tz": "Africa/Khartoum", "curr_es": "Libra sudanesa (SDG)", "curr_en": "Sudanese Pound (SDG)"},
  "Suriname": {"tz": "America/Paramaribo", "curr_es": "Dólar surinamés (SRD)", "curr_en": "Surinamese Dollar (SRD)"},
  "Sweden": {"tz": "Europe/Stockholm", "curr_es": "Corona sueca (SEK)", "curr_en": "Swedish Krona (SEK)"},
  "Switzerland": {"tz": "Europe/Zurich", "curr_es": "Franco suizo (CHF)", "curr_en": "Swiss Franc (CHF)"},
  "Syria": {"tz": "Asia/Damascus", "curr_es": "Libra siria (SYP)", "curr_en": "Syrian Pound (SYP)"},
  "Taiwan": {"tz": "Asia/Taipei", "curr_es": "Nuevo dólar taiwanés (TWD)", "curr_en": "New Taiwan Dollar (TWD)"},
  "Tajikistan": {"tz": "Asia/Dushanbe", "curr_es": "Somoni tayiko (TJS)", "curr_en": "Tajikistani Somoni (TJS)"},
  "Tanzania": {"tz": "Africa/Dar_es_Salaam", "curr_es": "Chelín tanzano (TZS)", "curr_en": "Tanzanian Shilling (TZS)"},
  "Thailand": {"tz": "Asia/Bangkok", "curr_es": "Baht tailandés (THB)", "curr_en": "Thai Baht (THB)"},
  "Timor-Leste": {"tz": "Asia/Dili", "curr_es": "Dólar estadounidense (USD)", "curr_en": "United States Dollar (USD)"},
  "Togo": {"tz": "Africa/Lome", "curr_es": "Franco CFA (XOF)", "curr_en": "West African CFA Franc (XOF)"},
  "Trinidad and Tobago": {"tz": "America/Port_of_Spain", "curr_es": "Dólar de Trinidad y Tobago (TTD)", "curr_en": "Trinidad and Tobago Dollar (TTD)"},
  "Tunisia": {"tz": "Africa/Tunis", "curr_es": "Dinar tunecino (TND)", "curr_en": "Tunisian Dinar (TND)"},
  "Turkey": {"tz": "Europe/Istanbul", "curr_es": "Lira turca (TRY)", "curr_en": "Turkish Lira (TRY)"},
  "Turkmenistan": {"tz": "Asia/Ashgabat", "curr_es": "Manat turcomano (TMT)", "curr_en": "Turkmenistani Manat (TMT)"},
  "Uganda": {"tz": "Africa/Kampala", "curr_es": "Chelín ugandés (UGX)", "curr_en": "Ugandan Shilling (UGX)"},
  "Ukraine": {"tz": "Europe/Kyiv", "curr_es": "Grivna ucraniana (UAH)", "curr_en": "Ukrainian Hryvnia (UAH)"},
  "United Arab Emirates": {"tz": "Asia/Dubai", "curr_es": "Dírham de los EAU (AED)", "curr_en": "United Arab Emirates Dirham (AED)"},
  "United Kingdom": {"tz": "Europe/London", "curr_es": "Libra esterlina (GBP)", "curr_en": "Pound Sterling (GBP)"},
  "United States of America": {"tz": "America/New_York", "curr_es": "Dólar estadounidense (USD)", "curr_en": "United States Dollar (USD)"},
  "Uruguay": {"tz": "America/Montevideo", "curr_es": "Peso uruguayo (UYU)", "curr_en": "Uruguayan Peso (UYU)"},
  "Uzbekistan": {"tz": "Asia/Tashkent", "curr_es": "Som uzbeko (UZS)", "curr_en": "Uzbekistani Som (UZS)"},
  "Vanuatu": {"tz": "Pacific/Efate", "curr_es": "Vatu vanuatuense (VUV)", "curr_en": "Vanuatu Vatu (VUV)"},
  "Venezuela": {"tz": "America/Caracas", "curr_es": "Bolívar digital (VES)", "curr_en": "Venezuelan Bolívar (VES)"},
  "Vietnam": {"tz": "Asia/Ho_Chi_Minh", "curr_es": "Dong vietnamita (VND)", "curr_en": "Vietnamese Dong (VND)"},
  "W. Sahara": {"tz": "Africa/El_Aaiun", "curr_es": "Dírham marroquí (MAD)", "curr_en": "Moroccan Dirham (MAD)"},
  "Yemen": {"tz": "Asia/Aden", "curr_es": "Rial yemení (YER)", "curr_en": "Yemeni Rial (YER)"},
  "Zambia": {"tz": "Africa/Lusaka", "curr_es": "Kwacha zambiano (ZMW)", "curr_en": "Zambian Kwacha (ZMW)"},
  "Zimbabwe": {"tz": "Africa/Harare", "curr_es": "ZiG / Dólar de Zimbabue", "curr_en": "Zimbabwe Gold (ZiG) / USD"}
}

# Attach extra properties to atlas
for k, v in raw_atlas.items():
    extra = COUNTRY_EXTRAS.get(k, {"tz": "UTC", "curr_es": "Moneda local", "curr_en": "Local currency"})
    v["tz"] = extra["tz"]
    v["es"]["curr"] = extra["curr_es"]
    v["en"]["curr"] = extra["curr_en"]

# OCEANS AND SEAS DATABASE (PRECISION ENCLOSED INLAND SEAS FIRST, THEN REGIONAL & OCEANS)
OCEANS_AND_SEAS = [
  # --- MARES INTERIORES Y CERRADOS (PRIORIDAD ALTA) ---
  {
    "id": "sea_of_azov",
    "name_es": "Mar de Azov",
    "name_en": "Sea of Azov",
    "icon": "🌊",
    "priority": 1,
    "radiusDeg": 2.5,
    "centroid": [36.5, 46.0],
    "bounds": {"minLon": 34.5, "maxLon": 39.5, "minLat": 45.0, "maxLat": 47.3},
    "es": {"type": "Mar Interior Somero", "area": "~39.000 km²", "depth": "Máx. 14 m (El más somero del planeta)", "fact": "Es el mar más somero del mundo; conectado al Mar Negro por el estrecho de Kerch."},
    "en": {"type": "Shallow Inland Sea", "area": "~39,000 km²", "depth": "Max. 14 m (Shallowest sea on Earth)", "fact": "The shallowest sea on Earth, connected to the Black Sea via the Kerch Strait."}
  },
  {
    "id": "caspian_sea",
    "name_es": "Mar Caspio",
    "name_en": "Caspian Sea",
    "icon": "🌊",
    "priority": 1,
    "radiusDeg": 5.5,
    "centroid": [50.5, 41.5],
    "bounds": {"minLon": 46.5, "maxLon": 55.0, "minLat": 36.5, "maxLat": 47.2},
    "es": {"type": "Mar Interior / Lago Endorreico", "area": "~371.000 km²", "depth": "Fosa Meridional (1.025 m)", "fact": "Es el cuerpo de agua interior cerrado más grande del planeta."},
    "en": {"type": "Inland Sea / Endorheic Basin", "area": "~371,000 km²", "depth": "South Caspian Depression (1,025 m)", "fact": "The largest enclosed inland body of water on Earth."}
  },
  {
    "id": "black_sea",
    "name_es": "Mar Negro",
    "name_en": "Black Sea",
    "icon": "🌊",
    "priority": 1,
    "radiusDeg": 5.5,
    "centroid": [34.5, 43.5],
    "bounds": {"minLon": 27.5, "maxLon": 42.0, "minLat": 40.8, "maxLat": 46.8},
    "es": {"type": "Mar Interior", "area": "~436.400 km²", "depth": "Máx. 2.212 m", "fact": "Conectado al Mediterráneo por el Bósforo; el 90% de sus aguas profundas carece de oxígeno."},
    "en": {"type": "Inland Sea", "area": "~436,400 km²", "depth": "Max. 2,212 m", "fact": "Connected to the Mediterranean via the Bosphorus; 90% of its deep water is anoxic."}
  },
  {
    "id": "red_sea",
    "name_es": "Mar Rojo",
    "name_en": "Red Sea",
    "icon": "🏝️",
    "priority": 1,
    "radiusDeg": 4.5,
    "centroid": [38.0, 21.0],
    "bounds": {"minLon": 32.2, "maxLon": 44.0, "minLat": 12.5, "maxLat": 28.5},
    "es": {"type": "Golfo / Mar Interior", "area": "~438.000 km²", "depth": "Fosa de Suakin (3.040 m)", "fact": "Conectado al Mediterráneo por el Canal de Suez y famoso por sus arrecifes de coral."},
    "en": {"type": "Inland Sea / Gulf", "area": "~438,000 km²", "depth": "Suakin Deep (3,040 m)", "fact": "Connected to the Mediterranean via the Suez Canal; famous for vibrant coral reefs."}
  },
  {
    "id": "persian_gulf",
    "name_es": "Golfo Pérsico / Arábigo",
    "name_en": "Persian Gulf",
    "icon": "🏝️",
    "priority": 1,
    "radiusDeg": 3.5,
    "centroid": [51.5, 26.5],
    "bounds": {"minLon": 47.8, "maxLon": 56.5, "minLat": 23.8, "maxLat": 30.5},
    "es": {"type": "Golfo Marino Interior", "area": "~251.000 km²", "depth": "Máx. 90 m", "fact": "Rico en perlas históricas y una de las rutas energéticas más transitadas del mundo."},
    "en": {"type": "Inland Marine Gulf", "area": "~251,000 km²", "depth": "Max. 90 m", "fact": "Historic pearl center and one of the most vital maritime energy choke points."}
  },
  {
    "id": "baltic_sea",
    "name_es": "Mar Báltico",
    "name_en": "Baltic Sea",
    "icon": "🌊",
    "priority": 2,
    "radiusDeg": 5.0,
    "centroid": [19.0, 58.0],
    "bounds": {"minLon": 10.0, "maxLon": 30.0, "minLat": 53.5, "maxLat": 66.0},
    "es": {"type": "Mar Interior Salobre", "area": "~377.000 km²", "depth": "Fosa de Landsort (459 m)", "fact": "El cuerpo de agua salobre interior más grande del mundo, con baja salinidad."},
    "en": {"type": "Brackish Inland Sea", "area": "~377,000 km²", "depth": "Landsort Deep (459 m)", "fact": "The largest body of brackish inland water in the world."}
  },
  {
    "id": "north_sea",
    "name_es": "Mar del Norte",
    "name_en": "North Sea",
    "icon": "🌊",
    "priority": 2,
    "radiusDeg": 4.5,
    "centroid": [3.0, 56.0],
    "bounds": {"minLon": -4.0, "maxLon": 10.0, "minLat": 51.0, "maxLat": 62.0},
    "es": {"type": "Mar Marginal", "area": "~570.000 km²", "depth": "Fosa de Noruega (725 m)", "fact": "Famoso por su rica pesca y plataformas de energía eólica marina."},
    "en": {"type": "Marginal Sea", "area": "~570,000 km²", "depth": "Norwegian Trench (725 m)", "fact": "Famous for rich fisheries and offshore wind energy platforms."}
  },
  {
    "id": "mediterranean_sea",
    "name_es": "Mar Mediterráneo",
    "name_en": "Mediterranean Sea",
    "icon": "🏝️",
    "priority": 2,
    "radiusDeg": 8.5,
    "centroid": [18.0, 35.0],
    "bounds": {"minLon": -5.5, "maxLon": 36.0, "minLat": 30.0, "maxLat": 45.0},
    "es": {"type": "Mar Interior", "area": "~2.5M km²", "depth": "Fosa de Calipso (5.267 m)", "fact": "Cuna de civilizaciones históricas (Grecia, Roma, Egipto, Fenicia)."},
    "en": {"type": "Inland Sea", "area": "~2.5M km²", "depth": "Calypso Deep (5,267 m)", "fact": "Cradle of ancient civilizations (Greece, Rome, Egypt, Phoenicia)."}
  },
  {
    "id": "caribbean_sea",
    "name_es": "Mar Caribe",
    "name_en": "Caribbean Sea",
    "icon": "🏝️",
    "priority": 2,
    "radiusDeg": 8.0,
    "centroid": [-75.0, 15.0],
    "bounds": {"minLon": -88.0, "maxLon": -60.0, "minLat": 9.0, "maxLat": 22.0},
    "es": {"type": "Mar Marginal", "area": "~2.75M km²", "depth": "Fosa de las Caimán (7.686 m)", "fact": "Famoso por sus aguas turquesas, arrecifes de coral y miles de islas tropicales."},
    "en": {"type": "Marginal Sea", "area": "~2.75M km²", "depth": "Cayman Trench (7,686 m)", "fact": "Famous for turquoise waters, coral reefs, and tropical islands."}
  },
  {
    "id": "gulf_of_mexico",
    "name_es": "Golfo de México",
    "name_en": "Gulf of Mexico",
    "icon": "🏝️",
    "priority": 2,
    "radiusDeg": 6.5,
    "centroid": [-90.0, 25.0],
    "bounds": {"minLon": -98.0, "maxLon": -81.0, "minLat": 18.0, "maxLat": 30.5},
    "es": {"type": "Golfo Oceánico", "area": "~1.6M km²", "depth": "Sima de Sigsbee (4.384 m)", "fact": "Origina la corriente del Golfo, que lleva calor hacia el norte de Europa."},
    "en": {"type": "Oceanic Gulf", "area": "~1.6M km²", "depth": "Sigsbee Deep (4,384 m)", "fact": "Origin of the Gulf Stream, carrying warmth to northern Europe."}
  },
  {
    "id": "sea_of_japan",
    "name_es": "Mar del Japón / Mar del Este",
    "name_en": "Sea of Japan / East Sea",
    "icon": "🌊",
    "priority": 2,
    "radiusDeg": 6.0,
    "centroid": [134.0, 40.0],
    "bounds": {"minLon": 127.0, "maxLon": 142.0, "minLat": 35.0, "maxLat": 52.0},
    "es": {"type": "Mar Marginal", "area": "~978.000 km²", "depth": "Cuenca de Japón (3.742 m)", "fact": "Casi cerrado por el archipiélago japonés y la península coreana."},
    "en": {"type": "Marginal Sea", "area": "~978,000 km²", "depth": "Japan Basin (3,742 m)", "fact": "Nearly enclosed by the Japanese archipelago and Korean peninsula."}
  },
  {
    "id": "coral_sea",
    "name_es": "Mar del Coral",
    "name_en": "Coral Sea",
    "icon": "🐠",
    "priority": 2,
    "radiusDeg": 8.0,
    "centroid": [155.0, -18.0],
    "bounds": {"minLon": 142.0, "maxLon": 170.0, "minLat": -30.0, "maxLat": -10.0},
    "es": {"type": "Mar Marginal", "area": "~4.8M km²", "depth": "Fosa de las Nuevas Hébridas (7.570 m)", "fact": "Alberga la Gran Barrera de Coral, el mayor ser vivo visible desde el espacio."},
    "en": {"type": "Marginal Sea", "area": "~4.8M km²", "depth": "New Hebrides Trench (7,570 m)", "fact": "Home to the Great Barrier Reef, the largest living structure on Earth."}
  },
  {
    "id": "arabian_sea",
    "name_es": "Mar Arábigo",
    "name_en": "Arabian Sea",
    "icon": "🌊",
    "priority": 2,
    "radiusDeg": 8.0,
    "centroid": [65.0, 16.0],
    "bounds": {"minLon": 50.0, "maxLon": 78.0, "minLat": 5.0, "maxLat": 26.0},
    "es": {"type": "Mar Marginal", "area": "~3.86M km²", "depth": "Cuenca Arábiga (4.652 m)", "fact": "Histórica ruta de comercio marítimo de las especias y la seda."},
    "en": {"type": "Marginal Sea", "area": "~3.86M km²", "depth": "Arabian Basin (4,652 m)", "fact": "Historic maritime trade route for spices and silks."}
  },
  {
    "id": "south_china_sea",
    "name_es": "Mar de la China Meridional",
    "name_en": "South China Sea",
    "icon": "🌊",
    "priority": 2,
    "radiusDeg": 8.0,
    "centroid": [114.0, 12.0],
    "bounds": {"minLon": 102.0, "maxLon": 122.0, "minLat": 1.0, "maxLat": 23.0},
    "es": {"type": "Mar Marginal", "area": "~3.5M km²", "depth": "Fosa de Manila (5.014 m)", "fact": "Por aquí transita más de un tercio del comercio marítimo de todo el planeta."},
    "en": {"type": "Marginal Sea", "area": "~3.5M km²", "depth": "Manila Trench (5,014 m)", "fact": "More than one-third of global maritime trade passes through here."}
  },
  {
    "id": "bering_sea",
    "name_es": "Mar de Bering",
    "name_en": "Bering Sea",
    "icon": "🧊",
    "priority": 2,
    "radiusDeg": 7.0,
    "centroid": [-175.0, 58.0],
    "bounds": {"minLon": 160.0, "maxLon": -158.0, "minLat": 50.0, "maxLat": 66.0},
    "es": {"type": "Mar Marginal", "area": "~2.0M km²", "depth": "Cuenca Bowers (4.097 m)", "fact": "Separa Asia de América a través del histórico Estrecho de Bering."},
    "en": {"type": "Marginal Sea", "area": "~2.0M km²", "depth": "Bowers Basin (4,097 m)", "fact": "Separates Asia from the Americas via the Bering Strait."}
  },
  # --- GRANDES OCÉANOS ---
  {
    "id": "pacific_north",
    "name_es": "Océano Pacífico Norte",
    "name_en": "North Pacific Ocean",
    "icon": "🌊",
    "priority": 3,
    "radiusDeg": 22.0,
    "centroid": [-160.0, 28.0],
    "bounds": {"minLon": 115.0, "maxLon": -95.0, "minLat": 0.0, "maxLat": 66.0},
    "es": {"type": "Océano", "area": "~165.2M km² (Total Pacífico)", "depth": "Fosa de las Marianas (11.034 m)", "fact": "Es el océano más grande y profundo del planeta Tierra."},
    "en": {"type": "Ocean", "area": "~165.2M km² (Total Pacific)", "depth": "Mariana Trench (11,034 m)", "fact": "The largest and deepest ocean on Earth."}
  },
  {
    "id": "pacific_south",
    "name_es": "Océano Pacífico Sur",
    "name_en": "South Pacific Ocean",
    "icon": "🌊",
    "priority": 3,
    "radiusDeg": 24.0,
    "centroid": [-130.0, -32.0],
    "bounds": {"minLon": 135.0, "maxLon": -68.0, "minLat": -60.0, "maxLat": 0.0},
    "es": {"type": "Océano", "area": "~165.2M km² (Total Pacífico)", "depth": "Fosa de Tonga (10.882 m)", "fact": "Alberga el 'Punto Nemo', el lugar más remoto y alejado de tierra firme."},
    "en": {"type": "Ocean", "area": "~165.2M km² (Total Pacific)", "depth": "Tonga Trench (10,882 m)", "fact": "Home to 'Point Nemo', the oceanic pole of inaccessibility."}
  },
  {
    "id": "atlantic_north",
    "name_es": "Océano Atlántico Norte",
    "name_en": "North Atlantic Ocean",
    "icon": "🌊",
    "priority": 3,
    "radiusDeg": 20.0,
    "centroid": [-42.0, 32.0],
    "bounds": {"minLon": -82.0, "maxLon": 0.0, "minLat": 0.0, "maxLat": 66.0},
    "es": {"type": "Océano", "area": "~106.5M km² (Total Atlántico)", "depth": "Fosa de Puerto Rico (8.376 m)", "fact": "Separa América de Europa y África; el 2.° océano más extenso."},
    "en": {"type": "Ocean", "area": "~106.5M km² (Total Atlantic)", "depth": "Puerto Rico Trench (8,376 m)", "fact": "Separates the Americas from Europe and Africa; 2nd largest."}
  },
  {
    "id": "atlantic_south",
    "name_es": "Océano Atlántico Sur",
    "name_en": "South Atlantic Ocean",
    "icon": "🌊",
    "priority": 3,
    "radiusDeg": 20.0,
    "centroid": [-18.0, -30.0],
    "bounds": {"minLon": -70.0, "maxLon": 22.0, "minLat": -60.0, "maxLat": 0.0},
    "es": {"type": "Océano", "area": "~106.5M km² (Total Atlántico)", "depth": "Fosa de las Sandwich del Sur (8.428 m)", "fact": "Rico en corrientes marinas y fauna antártica."},
    "en": {"type": "Ocean", "area": "~106.5M km² (Total Atlantic)", "depth": "South Sandwich Trench (8,428 m)", "fact": "Rich in marine currents and diverse wildlife."}
  },
  {
    "id": "indian_ocean",
    "name_es": "Océano Índico",
    "name_en": "Indian Ocean",
    "icon": "🌊",
    "priority": 3,
    "radiusDeg": 20.0,
    "centroid": [78.0, -18.0],
    "bounds": {"minLon": 20.0, "maxLon": 135.0, "minLat": -60.0, "maxLat": 30.0},
    "es": {"type": "Océano", "area": "~70.5M km²", "depth": "Fosa de Java (7.450 m)", "fact": "Es el océano más cálido del mundo y vital ruta de comercio."},
    "en": {"type": "Ocean", "area": "~70.5M km²", "depth": "Java Trench (7,450 m)", "fact": "The warmest ocean in the world and historic trading route."}
  },
  {
    "id": "arctic_ocean",
    "name_es": "Océano Ártico",
    "name_en": "Arctic Ocean",
    "icon": "🧊",
    "priority": 3,
    "radiusDeg": 16.0,
    "centroid": [0.0, 84.0],
    "bounds": {"minLon": -180.0, "maxLon": 180.0, "minLat": 66.0, "maxLat": 90.0},
    "es": {"type": "Océano Glacial", "area": "~14.0M km²", "depth": "Fosa de Molloy (5.550 m)", "fact": "Rodea el Polo Norte y está cubierto por banquisas polares de hielo."},
    "en": {"type": "Glacial Ocean", "area": "~14.0M km²", "depth": "Molloy Deep (5,550 m)", "fact": "Surrounds the North Pole and is covered by polar sea ice."}
  },
  {
    "id": "southern_ocean",
    "name_es": "Océano Antártico",
    "name_en": "Southern Ocean",
    "icon": "🧊",
    "priority": 3,
    "radiusDeg": 18.0,
    "centroid": [0.0, -68.0],
    "bounds": {"minLon": -180.0, "maxLon": 180.0, "minLat": -90.0, "maxLat": -58.0},
    "es": {"type": "Océano Glacial", "area": "~20.3M km²", "depth": "Fosa de las Sandwich del Sur (7.236 m)", "fact": "Rodea la Antártida con la potente corriente circumpolar."},
    "en": {"type": "Glacial Ocean", "area": "~20.3M km²", "depth": "South Sandwich Trench (7,236 m)", "fact": "Encircles Antarctica with the powerful Circumpolar Current."}
  }
]

print(f"Generated enriched atlas for {len(raw_atlas)} countries and {len(OCEANS_AND_SEAS)} oceans/seas!")
